export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const ALBUM_SONGS_REQUEST = "ALBUM_SONGS_REQUEST";
export const ALBUM_SONGS_REQUEST_SUCCESS = "ALBUM_SONGS_SUCCESS";
export const ALBUM_SONGS_REQUEST_FAIL = "ALBUM_SONGS_FAIL";

export const ALBUM_CREATE_REQUEST = "ALBUM_CREATE_REQUEST";
export const ALBUM_CREATE_SUCCESS = "ALBUM_CREATE_SUCCESS";
export const ALBUM_CREATE_FAIL = "ALBUM_CREATE_FAIL";

export const ADD_SONG_REQUEST = "ADD_SONG_REQUEST";
export const ADD_SONG_SUCCESS = "ADD_SONG_SUCCESS";
export const ADD_SONG_FAIL = "ADD_SONG_FAIL";

export const PLAY_SONG_REQUEST = "PLAY_SONG_REQUEST";
export const PLAY_SONG_SUCCESS = "PLAY_SONG_SUCCESS";
export const PLAY_SONG_FAIL = "PLAY_SONG_FAIL";

export const ALBUM_LIST_REQUEST = "ALBUM_LIST_REQUEST";
export const ALBUM_LIST_SUCCESS = "ALBUM_LIST_SUCCESS";
export const ALBUM_LIST_FAIL = "ALBUM_LIST_FAIL";
